feedback/accounts/urls.py
from django.conf.urls import url
from .views import login_user, register_user, logout_user

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^register/$', register_user, name='register'),
]

feedback/fback/urls.py
from django.conf.urls import url
from .views import FeedbackCreateView, success
from django.contrib.auth.decorators import login_required

app_name = 'feedback'

urlpatterns = [
    url(r'^form/$', login_required(FeedbackCreateView.as_view()), name='form'),
    url(r'^success/$',  login_required(success), name='success')
]

feedback/feedback/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy
from .views import home

admin.site.site_header = ugettext_lazy('Feedback Admin')    # Text to put in each page's <h1> (and above login form).
admin.site.site_title = ugettext_lazy('Feedback')   # Text to put at the end of each page's <title>.
admin.site.index_title = ugettext_lazy('Feedback Administration')   # Text to put at the top of the admin index page.

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^feedback/', include('fback.urls')),
    url(r'^$', home, name='home_page'),
]

feedback/accounts/models.py
from django.db import models

# Create your models here.

feedback/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.validators import RegexValidator


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True, min_length=2,
                                 widget=forms.TextInput(attrs={
                                     'class': 'form-control',
                                     'placeholder': 'First Name'
                                 }))
    last_name = forms.CharField(required=True, min_length=2,
                                widget=forms.TextInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Last Name'
                                }))
    email = forms.CharField(required=True,
                            widget=forms.EmailInput(attrs={
                                'class': 'form-control',
                                'placeholder': 'Email'
                            }))
    username = forms.CharField(
        validators=[
            RegexValidator(
                regex='^[a-zA-Z0-9]*$',
                message='Username must be Alphanumeric!',
                code='invalid_username'
            ),
        ],
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        })
    )
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Password'
                                }))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Confirm Password'
                                }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username'
                               }))
    password = forms.CharField(max_length=100,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Password'
                               }))

feedback/accounts/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse, reverse_lazy
from .forms import UserRegistrationForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_user(request):
    next_page = request.GET.get('next')
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home_page'))

    if request.method == 'POST':
        form = LoginForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = authenticate(username=form.cleaned_data.get('username'),
                                password=form.cleaned_data.get('password'))

            if user is not None:
                if user.is_active:
                    login(request, user)

                    success_message = "Welcome {}! You have been logged in.".format(username.title())
                    messages.success(request, success_message)

                    if next_page:
                        return HttpResponseRedirect(next_page)

                    return HttpResponseRedirect(reverse('home_page'))

                messages.error(request, "Account deactivated! Email admin for help.")

            messages.error(request, "Login failed! Username and/or password invalid")

    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form, })


def register_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home_page'))

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            user = authenticate(
                username=username,
                password=form.cleaned_data.get('password1'))

            if user and user.is_active:
                login(request, user)

                success_message = "Account created successfully! Welcome {}!".format(username.title())
                messages.success(request, success_message)

                return HttpResponseRedirect(reverse('home_page'))

            messages.error(request, "Account registered! Check email for admin message.")

        messages.error(request, "Registration failed! Check listed errors.")

    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form, })


def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out.")

    return HttpResponseRedirect(reverse('home_page'))

feedback/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block page_title %}Login{% endblock %}

{% block content %}
<style>
    body {
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #eee;
    }

    .form-signin {
      max-width: 330px;
      padding: 15px;
      margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
      margin-bottom: 10px;
    }
    .form-signin .checkbox {
      font-weight: normal;
    }
    .form-signin .form-control {
      position: relative;
      height: auto;
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
      padding: 10px;
      font-size: 16px;
    }
    .form-signin .form-control:focus {
      z-index: 2;
    }
    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
</style>


<form action="" method="post" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign in</h2>
    <label for="{{ form.username.id_for_label }}" class="sr-only">
        {{ form.username.label }}
    </label>
    {{ form.username }}

    <label for="{{ form.password.id_for_label }}" class="sr-only">{{ form.password.label }}</label>
    {{ form.password }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    <span>or <strong>
        <a href="{% url 'accounts:register' %}">sign up</a>
    </strong></span>
</form>

{% endblock %}

feedback/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block page_title %}Sign Up{% endblock %}

{% block content %}
<style>
    body {
      padding-top: 40px;
      padding-bottom: 40px;
      background-color: #eee;
    }

    .form-signin {
      max-width: 330px;
      padding: 15px;
      margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
      margin-bottom: 10px;
    }
    .form-signin .checkbox {
      font-weight: normal;
    }
    .form-signin .form-control {
      position: relative;
      height: auto;
      -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
              box-sizing: border-box;
      padding: 10px;
      font-size: 16px;
    }
    .form-signin .form-control:focus {
      z-index: 2;
    }
    .form-signin input[type="email"] {
      margin-bottom: -1px;
      border-bottom-right-radius: 0;
      border-bottom-left-radius: 0;
    }
    .form-signin input[type="password"] {
      margin-bottom: 10px;
      border-top-left-radius: 0;
      border-top-right-radius: 0;
    }
</style>


<form action="" method="post" class="form-signin">
    {% csrf_token %}
    <h2 class="form-signin-heading">Please sign up</h2>

    <label for="{{ form.first_name.id_for_label }}" class="sr-only">
        {{ form.first_name.label }}
    </label>
    {{ form.first_name }}

    <label for="{{ form.last_name.id_for_label }}" class="sr-only">
        {{ form.last_name.label }}
    </label>
    {{ form.last_name }}

    <label for="{{ form.username.id_for_label }}" class="sr-only">
        {{ form.username.label }}
    </label>
    {{ form.username }}

    <label for="{{ form.email.id_for_label }}" class="sr-only">
        {{ form.email.label }}
    </label>
    {{ form.email }}

    <label for="{{ form.password1.id_for_label }}" class="sr-only">
        {{ form.password1.label }}
    </label>
    {{ form.password1 }}
    <label for="{{ form.password2.id_for_label }}" class="sr-only">
        {{ form.password2.label }}
    </label>
    {{ form.password2 }}
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
    <span>or <strong>
        <a href="{% url 'accounts:login' %}">login</a>
    </strong></span>
</form>

{% endblock %}