feedback/accounts/urls.py
from django.conf.urls import url
from .views import login_user, register_user, logout_user

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_user, name='login'),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^register/$', register_user, name='register'),
]

feedback/fback/urls.py
from django.conf.urls import url
from .views import FeedbackCreateView, success
from django.contrib.auth.decorators import login_required

app_name = 'feedback'

urlpatterns = [
    url(r'^form/$', login_required(FeedbackCreateView.as_view()), name='form'),
    url(r'^success/$',  login_required(success), name='success')
]

feedback/feedback/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.utils.translation import ugettext_lazy
from .views import home

admin.site.site_header = ugettext_lazy('Feedback Admin')    # Text to put in each page's <h1> (and above login form).
admin.site.site_title = ugettext_lazy('Feedback')   # Text to put at the end of each page's <title>.
admin.site.index_title = ugettext_lazy('Feedback Administration')   # Text to put at the top of the admin index page.

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^feedback/', include('fback.urls')),
    url(r'^$', home, name='home_page'),
]

feedback/accounts/models.py
from django.db import models

# Create your models here.

feedback/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.validators import RegexValidator


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(required=True, min_length=2,
                                 widget=forms.TextInput(attrs={
                                     'class': 'form-control',
                                     'placeholder': 'First Name'
                                 }))
    last_name = forms.CharField(required=True, min_length=2,
                                widget=forms.TextInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Last Name'
                                }))
    email = forms.CharField(required=True,
                            widget=forms.EmailInput(attrs={
                                'class': 'form-control',
                                'placeholder': 'Email'
                            }))
    username = forms.CharField(
        validators=[
            RegexValidator(
                regex='^[a-zA-Z0-9]*$',
                message='Username must be Alphanumeric!',
                code='invalid_username'
            ),
        ],
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Username'
        })
    )
    password1 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Password'
                                }))
    password2 = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                    'placeholder': 'Confirm Password'
                                }))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Username'
                               }))
    password = forms.CharField(max_length=100,
                               widget=forms.PasswordInput(attrs={
                                   'class': 'form-control',
                                   'placeholder': 'Password'
                               }))

feedback/accounts/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse, reverse_lazy
from .forms import UserRegistrationForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_user(request):
    next_page = request.GET.get('next')
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home_page'))

    if request.method == 'POST':
        form = LoginForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            user = authenticate(username=form.cleaned_data.get('username'),
                                password=form.cleaned_data.get('password'))

            if user is not None:
                if user.is_active:
                    login(request, user)

                    success_message = "Welcome {}! You have been logged in.".format(username.title())
                    messages.success(request, success_message)

                    if next_page:
                        return HttpResponseRedirect(next_page)

                    return HttpResponseRedirect(reverse('home_page'))

                messages.error(request, "Account deactivated! Email admin for help.")

            messages.error(request, "Login failed! Username and/or password invalid")

    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {'form': form, })


def register_user(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('home_page'))

    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            user = authenticate(
                username=username,
                password=form.cleaned_data.get('password1'))

            if user and user.is_active:
                login(request, user)

                success_message = "Account created successfully! Welcome {}!".format(username.title())
                messages.success(request, success_message)

                return HttpResponseRedirect(reverse('home_page'))

            messages.error(request, "Account registered! Check email for admin message.")

        messages.error(request, "Registration failed! Check listed errors.")

    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form, })


def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out.")

    return HttpResponseRedirect(reverse('home_page'))

feedback/accounts/templates/base.html
{% load staticfiles %}
{% load static %}

<html>

    <head>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <title>Feedback | {% block page_title %}{% endblock %}</title>
    </head>

    <body>
        <style>
            body {
              padding-top: 40px;
              padding-bottom: 40px;
              background-color: #eee;
            }

            .form-signin {
              max-width: 330px;
              padding: 15px;
              margin: 0 auto;
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
              margin-bottom: 10px;
            }
            .form-signin .checkbox {
              font-weight: normal;
            }
            .form-signin .form-control {
              position: relative;
              height: auto;
              -webkit-box-sizing: border-box;
                 -moz-box-sizing: border-box;
                      box-sizing: border-box;
              padding: 10px;
              font-size: 16px;
            }
            .form-signin .form-control:focus {
              z-index: 2;
            }
            .form-signin input[type="email"] {
              margin-bottom: -1px;
              border-bottom-right-radius: 0;
              border-bottom-left-radius: 0;
            }
            .form-signin input[type="password"] {
              margin-bottom: 10px;
              border-top-left-radius: 0;
              border-top-right-radius: 0;
            }
        </style>

        <div class="container">
            <!-- Static navbar -->
              <nav class="navbar navbar-default">
                <div class="container-fluid">
                  <div class="navbar-header">
                    <a class="navbar-brand" href="#">Feedback</a>
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="{% url 'home_page' %}">Home</a></li>
                        {% if request.user.is_authenticated %}
                        <li><a href="{% url 'feedback:form' %}">Feedback</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        {% endif %}

                    </ul>
                    {% if request.user.is_staff or request.user.is_superuser %}
                    <ul class="nav navbar-nav navbar-right">
                      <li class="active"><a href="{% url 'admin:index' %}">Admin</a></li>
                    </ul>
                    {% endif %}
                  </div>
                </div>
              </nav>

            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
            {% endfor %}

            {% for key, value in form.errors.items %}
              <div class="alert alert-warning" role="alert">{{ value }}</div>
            {% endfor %}

            {% for error in form.non_field_errors %}
              <div class="alert alert-warning" role="alert">{{ error }}</div>
            {% endfor %}
            {% block content %}{% endblock %}
        </div>

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </body>

</html>

feedback/accounts/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
  <h1>Hello!</h1>
  <p>This is a simple application to get your feedback.</p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %}" role="button">Sign in</a></p>
</div>

{% endblock %}